# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "UCI ID", # <clean_world_champs_25>
  "Nr Name / UCI MTB Team", # <clean_world_champs_25>
  "name_uci_mtb_team", # <clean_world_champs_25>
  "i1_i2", # <clean_world_champs_25>
  "i3_i4", # <clean_world_champs_25>
  "name", # <clean_world_champs_25>
  "I1 / I2", # <clean_world_champs_25>
  "I3 / I4", # <clean_world_champs_25>
  "Time", # <clean_world_champs_25>
  "time", # <clean_world_champs_25>
  "time_from_leader", # <clean_world_champs_25>
  "nr", # <clean_world_champs_25>
  "uci_id", # <clean_world_champs_25>
  "speed", # <clean_world_champs_25>
  "nat", # <clean_world_champs_25>
  "yob", # <clean_world_champs_25>
  "split_1", # <clean_world_champs_25>
  "split_2", # <clean_world_champs_25>
  "split_3", # <clean_world_champs_25>
  "split_4", # <clean_world_champs_25>
  "dnf", # <clean_world_champs_25>
  "dsq", # <clean_world_champs_25>
  "dns", # <clean_world_champs_25>
  "UCI ID", # <clean_results_24>
  "Nr Name / UCI MTB Team", # <clean_results_24>
  "x2", # <clean_results_24>
  "name_uci_mtb_team", # <clean_results_24>
  "i1_i2", # <clean_results_24>
  "i3_i4", # <clean_results_24>
  "protected", # <clean_results_24>
  "name", # <clean_results_24>
  "I1 / I2", # <clean_results_24>
  "I3 / I4", # <clean_results_24>
  "Time", # <clean_results_24>
  "time", # <clean_results_24>
  "time_from_leader", # <clean_results_24>
  "nr", # <clean_results_24>
  "uci_id", # <clean_results_24>
  "speed", # <clean_results_24>
  "points", # <clean_results_24>
  "uci_team", # <clean_results_24>
  "nat", # <clean_results_24>
  "yob", # <clean_results_24>
  "split_1", # <clean_results_24>
  "split_2", # <clean_results_24>
  "split_3", # <clean_results_24>
  "split_4", # <clean_results_24>
  "dnf", # <clean_results_24>
  "dsq", # <clean_results_24>
  "dns", # <clean_results_24>
  "UCI ID", # <clean_results_25>
  "Nr Name / UCI MTB Team", # <clean_results_25>
  "name_uci_mtb_team", # <clean_results_25>
  "i1_i2", # <clean_results_25>
  "i3_i4", # <clean_results_25>
  "name", # <clean_results_25>
  "I1 / I2", # <clean_results_25>
  "I3 / I4", # <clean_results_25>
  "Time", # <clean_results_25>
  "time", # <clean_results_25>
  "time_from_leader", # <clean_results_25>
  "nr", # <clean_results_25>
  "uci_id", # <clean_results_25>
  "speed", # <clean_results_25>
  "points", # <clean_results_25>
  "uci_team", # <clean_results_25>
  "nat", # <clean_results_25>
  "yob", # <clean_results_25>
  "split_1", # <clean_results_25>
  "split_2", # <clean_results_25>
  "split_3", # <clean_results_25>
  "split_4", # <clean_results_25>
  "dnf", # <clean_results_25>
  "dsq", # <clean_results_25>
  "dns", # <clean_results_25>
  "Nr", # <clean_timed_training_24>
  "Rank", # <clean_timed_training_24>
  "Name / UCI MTB Team", # <clean_timed_training_24>
  "NAT", # <clean_timed_training_24>
  "Speed...5", # <clean_timed_training_24>
  "Splits...6", # <clean_timed_training_24>
  "Time...7", # <clean_timed_training_24>
  "Speed...8", # <clean_timed_training_24>
  "Splits...9", # <clean_timed_training_24>
  "Time...10", # <clean_timed_training_24>
  "Speed...11", # <clean_timed_training_24>
  "Splits...12", # <clean_timed_training_24>
  "Time...13", # <clean_timed_training_24>
  "Time...14", # <clean_timed_training_24>
  "name", # <clean_timed_training_24>
  "best_time_from_leader", # <clean_timed_training_24>
  "nr", # <clean_timed_training_24>
  "uci_team", # <clean_timed_training_24>
  "nat", # <clean_timed_training_24>
  "run_1_speed", # <clean_timed_training_24>
  "run_1_time", # <clean_timed_training_24>
  "run_2_speed", # <clean_timed_training_24>
  "run_2_time", # <clean_timed_training_24>
  "run_3_speed", # <clean_timed_training_24>
  "run_3_time", # <clean_timed_training_24>
  "best_time", # <clean_timed_training_24>
  "Nr", # <clean_timed_training_25>
  "Rank", # <clean_timed_training_25>
  "Name / UCI MTB Team", # <clean_timed_training_25>
  "Splits...4", # <clean_timed_training_25>
  "Time...5", # <clean_timed_training_25>
  "Splits...6", # <clean_timed_training_25>
  "Time...7", # <clean_timed_training_25>
  "Splits...8", # <clean_timed_training_25>
  "Time...9", # <clean_timed_training_25>
  "Splits...10", # <clean_timed_training_25>
  "Time...11", # <clean_timed_training_25>
  "Splits...12", # <clean_timed_training_25>
  "Time...13", # <clean_timed_training_25>
  "Time...14", # <clean_timed_training_25>
  "name", # <clean_timed_training_25>
  "best_time_from_leader", # <clean_timed_training_25>
  "nr", # <clean_timed_training_25>
  "uci_team", # <clean_timed_training_25>
  "run_1_speed_kmh", # <clean_timed_training_25>
  "run_1_time", # <clean_timed_training_25>
  "run_2_speed_kmh", # <clean_timed_training_25>
  "run_2_time", # <clean_timed_training_25>
  "run_3_speed_kmh", # <clean_timed_training_25>
  "run_3_time", # <clean_timed_training_25>
  "run_4_speed_kmh", # <clean_timed_training_25>
  "run_4_time", # <clean_timed_training_25>
  "run_5_speed_kmh", # <clean_timed_training_25>
  "run_5_time", # <clean_timed_training_25>
  "best_time", # <clean_timed_training_25>
  NULL
))
